# Micronaut Application Configuration
micronaut.application.name=micronaut-service-scheduling-rest-api

# PostgreSQL Datasource Configuration
# datasources.default.db-type=postgresql
# datasources.default.dialect=POSTGRES
# datasources.default.driver-class-name=org.postgresql.Driver
# datasources.default.url=jdbc:postgresql://localhost:5432/service_db
# datasources.default.username=postgres

# MySQL Datasource Configuration
datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.url=jdbc:mysql://localhost:3306/service_db?allowPublicKeyRetrieval=true&useSSL=false
datasources.default.username=root

datasources.default.password=trabalhoSD
datasources.default.schema-generate=CREATE_DROP

# Security Base Configuration
micronaut.security.enabled=true
micronaut.security.authentication=bearer

# Habilitar Endpoints de Seguran�a (Obrigat�rio para evitar 404)
micronaut.security.endpoints.login.enabled=true
micronaut.security.endpoints.logout.enabled=true

micronaut.security.token.jwt.signatures.secret.generator.secret=esta_chave_precisa_d_mais_d_32_caracteres_aqui_para_funcionar
micronaut.security.token.jwt.generator.access-token-expiration=1800

auth.username=${APP_AUTH_USER:usuario}
auth.password=${APP_AUTH_PASS:senha123}

micronaut.security.rules.enabled=true

# faz com que para toda url, o micronaut verifique se h� a defini��o de isAnonymous(), se h�, permite realizar a req sem autentica��o
micronaut.security.intercept-url-map[0].pattern=/**
micronaut.security.intercept-url-map[0].access=isAnonymous()