# Enable the security engine
micronaut.security.enabled=true

# Tell Micronaut to use JWT/Bearer tokens
micronaut.security.authentication=bearer

# Enable the built-in /login endpoint
micronaut.security.endpoints.login.enabled=true

# JWT Secret (Must be at least 256-bit / 32 characters for HS256)
micronaut.security.token.jwt.signatures.secret.generator.secret=esta_chave_precisa_d_mais_d_32_caracteres_aqui_para_funcionar
auth.username=${APP_AUTH_USER:usuario}
auth.password=${APP_AUTH_PASS:senha123}