# Micronaut Application Config
micronaut.application.name=micronaut-service-scheduling-rest-api

# ==========================================
# Database Config (MySQL)
# ==========================================
datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
# Em produção, mudar para useSSL=true para proteger a conexão com o banco
datasources.default.url=jdbc:mysql://localhost:3306/service_db?allowPublicKeyRetrieval=true&useSSL=false
datasources.default.username=root
datasources.default.password=trabalhoSD
datasources.default.schema-generate=CREATE_DROP

# ==========================================
# Security Base Config
# ==========================================
micronaut.security.enabled=true
micronaut.security.authentication=bearer

# Habilita Endpoints de Login
micronaut.security.endpoints.login.enabled=true
micronaut.security.endpoints.logout.enabled=true

# Configuração do Token JWT
micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_GENERATOR_SIGNATURE_SECRET:esta_chave_precisa_d_mais_d_32_caracteres_aqui_para_funcionar}
micronaut.security.token.jwt.generator.access-token-expiration=1800

# Credenciais de Teste
auth.username=${APP_AUTH_USER:usuario}
auth.password=${APP_AUTH_PASS:senha123}

# ==========================================
# Controle de Acesso e Regras
# ==========================================
micronaut.security.rules.enabled=true

# R1: Permite login sem token
micronaut.security.intercept-url-map[0].pattern=/login
micronaut.security.intercept-url-map[0].access=isAnonymous()

# R2: Bloqueia o resto da API para usuários não autenticados
micronaut.security.intercept-url-map[1].pattern=/**
micronaut.security.intercept-url-map[1].access=isAuthenticated()

# ==========================================
# Proteções Adicionais
# ==========================================

micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins=*
micronaut.server.cors.configurations.web.allowed-methods=GET, POST, PUT, DELETE, OPTIONS

# Impede que o Micronaut envie detalhes internos do servidor em erros 404/500
micronaut.server.errors.status.404.not-found.enabled=true